export function cartela() {
  let numeros = [
    { numero: 1, status: "disponivel" },
    { numero: 2, status: "vendido" },
    { numero: 3, status: "disponivel" },
    { numero: 4, status: "reservado" },
    { numero: 5, status: "disponivel" },
    { numero: 6, status: "disponivel" },
    { numero: 7, status: "vendido" },
    { numero: 8, status: "disponivel" },
    { numero: 9, status: "reservado" },
    { numero: 10, status: "disponivel" },
    { numero: 11, status: "disponivel" },
    { numero: 12, status: "vendido" },
    { numero: 13, status: "disponivel" },
    { numero: 14, status: "reservado" },
    { numero: 15, status: "disponivel" },
    { numero: 16, status: "disponivel" },
    { numero: 17, status: "vendido" },
    { numero: 18, status: "disponivel" },
    { numero: 19, status: "reservado" },
    { numero: 20, status: "disponivel" },
    { numero: 21, status: "disponivel" },
    { numero: 22, status: "vendido" },
    { numero: 23, status: "disponivel" },
    { numero: 24, status: "reservado" },
    { numero: 25, status: "disponivel" },
    { numero: 26, status: "disponivel" },
    { numero: 27, status: "vendido" },
    { numero: 28, status: "disponivel" },
    { numero: 29, status: "reservado" },
    { numero: 30, status: "disponivel" },
    { numero: 31, status: "disponivel" },
    { numero: 32, status: "vendido" },
    { numero: 33, status: "disponivel" },
    { numero: 34, status: "reservado" },
    { numero: 35, status: "disponivel" },
    { numero: 36, status: "disponivel" },
    { numero: 37, status: "vendido" },
    { numero: 38, status: "disponivel" },
    { numero: 39, status: "reservado" },
    { numero: 40, status: "disponivel" },
    { numero: 41, status: "disponivel" },
    { numero: 42, status: "vendido" },
    { numero: 43, status: "disponivel" },
    { numero: 44, status: "reservado" },
    { numero: 45, status: "disponivel" },
    { numero: 46, status: "disponivel" },
    { numero: 47, status: "vendido" },
    { numero: 48, status: "disponivel" },
    { numero: 49, status: "reservado" },
    { numero: 50, status: "disponivel" },
  ];
  return numeros;
}
